# Generated by Django 4.2.7 on 2024-04-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('Новая', 'Новая'), ('В работе', 'В работе'), ('Завершена', 'Завершена')], default='Новая', max_length=20, verbose_name='Статус')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Очень высокий'), (5, 'Критический')], default=3, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports_as_project', to='quality_control.bugreport', verbose_name='Проект')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports_as_task', to='quality_control.bugreport', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Баг-репорт',
                'verbose_name_plural': 'Баг-репорты',
            },
        ),
    ]
